### ISSUE TITLE
Adding support for Laravel 6.0?

### ISSUE THREAD

**Issue by lasselehtinen** [mingalevme/illuminate-uqueue#5]
Would it be possible to add support for Laravel 6 by updating the depencies for illuminate/queue  v6? I would have created a pull request but got stuck with travis memory issues and predis/predis requirement being dev. I might give it another try later.

**Comment by mingalevme** [comment]
Hi, I'll try to add support next two weeks.

**Comment by mingalevme** [comment]
https://travis-ci.org/mingalevme/illuminate-uqueue/builds/586897698

**Comment by lasselehtinen** [comment]
Thanks a lot!
